<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../common/Mod.targets"/>

    <PropertyGroup>
        <BereftModRefs>CalamityMod;SOTS;QuestBooks</BereftModRefs>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BereftCompatibility\BereftCompatibility.csproj"/>
    </ItemGroup>

    <Import Project="../common/ModRefs.targets"/>

</Project>
