// <auto-generated>
//     Generated by tools/generate_quests.py from tools/quest_steps.json.
// </auto-generated>

using Terraria.ID;
using Terraria.ModLoader;

namespace BereftSouls.Quests.Steps;

public sealed class ObtainSolidifier : ObtainItemQuest
{
    protected override int ItemType => ItemID.Solidifier;
}

public sealed class SetWulfrumArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Wulfrum.WulfrumHat>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Wulfrum.WulfrumJacket>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Wulfrum.WulfrumOveralls>()];

    protected internal override int RewardType => ItemID.HermesBoots;
}

public sealed class SetSnowRuffianArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.SnowRuffian.SnowRuffianMask>(), ModContent.ItemType<global::CalamityMod.Items.Armor.SnowRuffian.SnowRuffianChestplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.SnowRuffian.SnowRuffianGreaves>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.CoinofDeceit>();
}

public sealed class FarmFragmentOfNature : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.FragmentOfNature>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.RegenerationPotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmFragmentOfEarth : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.FragmentOfEarth>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.SpelunkerPotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmFragmentOfTide : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.FragmentOfTide>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.GillsPotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmFragmentOfOtherworld : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.FragmentOfOtherworld>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.FeatherfallPotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmStormlionMandible : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.StormlionMandible>();

    protected override int Stack => 5;
}

public sealed class FarmSulphuricScale : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.SulphuricScale>();

    protected override int Stack => 10;
}

public sealed class CraftFrigidBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Permafrost.FrigidBar>();

    protected override int Stack => 12;

    protected internal override int RewardType => ItemID.WarmthPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetFrigidArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Permafrost.FrigidCrown>(), ModContent.ItemType<global::SOTS.Items.Permafrost.FrigidRobe>(), ModContent.ItemType<global::SOTS.Items.Permafrost.FrigidGreaves>()];

    protected internal override int RewardType => ItemID.IceSkates;
}

public sealed class CraftVibrantBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Earth.VibrantBar>();

    protected override int Stack => 10;
}

public sealed class SetVibrantArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Earth.VibrantHelmet>(), ModContent.ItemType<global::SOTS.Items.Earth.VibrantChestplate>(), ModContent.ItemType<global::SOTS.Items.Earth.VibrantLeggings>()];

    protected internal override int RewardType => ItemID.SharkToothNecklace;
}

public sealed class CraftDesertMedallion : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.DesertMedallion>();
}

public sealed class ObtainPearlShard : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.PearlShard>();

    protected override int Stack => 4;
}

public sealed class SetVictideArmorMelee : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Victide.VictideHeadMelee>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Victide.VictideBreastplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Victide.VictideGreaves>()];

    protected internal override int RewardType => ItemID.FeralClaws;
}

public sealed class ObtainPrismShard : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.SunkenSea.PrismShard>();

    protected override int Stack => 3;
}

public sealed class CraftSuspiciousLookingCandle : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Earth.Glowmoth.SuspiciousLookingCandle>();
}

public sealed class CraftDecapoditaSprout : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.DecapoditaSprout>();
}

public sealed class EquipFungalClump : EquipItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Accessories.FungalClump>();
}

public sealed class MineAerialiteOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.AerialiteOre>();

    protected override int Stack => 15;
}

public sealed class CraftAerialiteBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AerialiteBar>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.IronskinPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetAerospecArmorRogue : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Aerospec.AerospecHeadRogue>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Aerospec.AerospecBreastplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Aerospec.AerospecLeggings>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.RaidersTalisman>();
}

public sealed class FarmPeanuts : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Slime.Peanut>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.SwiftnessPotion;

    protected internal override int RewardStack => 2;
}

public sealed class CraftJarOfPeanuts : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Slime.JarOfPeanuts>();
}

public sealed class ObtainWormwood : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Slime.Wormwood>();

    protected override int Stack => 25;
}

public sealed class SetNatureArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Nature.NatureWreath>(), ModContent.ItemType<global::SOTS.Items.Nature.NatureShirt>(), ModContent.ItemType<global::SOTS.Items.Nature.NatureLeggings>()];

    protected internal override int RewardType => ItemID.FeralClaws;
}

public sealed class FarmBlightedGel : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.BlightedGel>();

    protected override int Stack => 40;

    protected internal override int RewardType => ItemID.HealingPotion;

    protected internal override int RewardStack => 5;
}

public sealed class CraftOverloadedSludge : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.OverloadedSludge>();
}

public sealed class ObtainPurifiedGel : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.PurifiedGel>();

    protected override int Stack => 18;
}

public sealed class SetStatigelArmorMagic : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Statigel.StatigelHeadMagic>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Statigel.StatigelArmor>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Statigel.StatigelGreaves>()];

    protected internal override int RewardType => ItemID.BandofStarpower;
}

public sealed class CraftAbeemination : ObtainItemQuest
{
    protected override int ItemType => ItemID.Abeemination;
}

public sealed class ObtainBeeWax : ObtainItemQuest
{
    protected override int ItemType => ItemID.BeeWax;

    protected override int Stack => 14;
}

public sealed class ObtainCursedMatter : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Pyramid.CursedMatter>();

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.MagicPowerPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetCursedArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Pyramid.CursedHood>(), ModContent.ItemType<global::SOTS.Items.Pyramid.CursedRobe>()];

    protected internal override int RewardType => ItemID.CelestialMagnet;
}

public sealed class ObtainHellforge : ObtainItemQuest
{
    protected override int ItemType => ItemID.Hellforge;

    protected internal override int RewardType => ItemID.ObsidianSkinPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftHellstoneBars : ObtainItemQuest
{
    protected override int ItemType => ItemID.HellstoneBar;

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.MiningPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetMoltenArmor : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.MoltenHelmet, ItemID.MoltenBreastplate, ItemID.MoltenGreaves];

    protected internal override int RewardType => ItemID.SharkToothNecklace;
}

public sealed class ObtainGuideVoodooDoll : ObtainItemQuest
{
    protected override int ItemType => ItemID.GuideVoodooDoll;

    protected internal override int RewardType => ItemID.IronskinPotion;

    protected internal override int RewardStack => 3;
}

public sealed class ObtainEarthenPlating : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.EarthenPlating>();

    protected override int Stack => 15;
}

public sealed class ObtainHardlightFabricator : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Planetarium.Furniture.HardlightFabricator>();
}

public sealed class CraftStarlightAlloy : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Planetarium.FromChests.StarlightAlloy>();

    protected override int Stack => 12;
}

public sealed class SetTwilightAssassinArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Planetarium.FromChests.TwilightAssassinsCirclet>(), ModContent.ItemType<global::SOTS.Items.Planetarium.FromChests.TwilightAssassinsChestplate>(), ModContent.ItemType<global::SOTS.Items.Planetarium.FromChests.TwilightAssassinsLeggings>()];

    protected internal override int RewardType => ItemID.FeralClaws;
}

public sealed class CraftDeerThing : ObtainItemQuest
{
    protected override int ItemType => ItemID.DeerThing;
}

public sealed class FarmSoulsOfLight : ObtainItemQuest
{
    protected override int ItemType => ItemID.SoulofLight;

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.ShinePotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmSoulsOfNight : ObtainItemQuest
{
    protected override int ItemType => ItemID.SoulofNight;

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.NightOwlPotion;

    protected internal override int RewardStack => 3;
}

public sealed class ObtainMythrilAnvil : ObtainItemQuest
{
    protected override int ItemType => ItemID.MythrilAnvil;
}

public sealed class ObtainOrichalcumAnvil : ObtainItemQuest
{
    protected override int ItemType => ItemID.OrichalcumAnvil;
}

public sealed class CraftMechanicalWorm : ObtainItemQuest
{
    protected override int ItemType => ItemID.MechanicalWorm;
}

public sealed class CraftMechanicalEye : ObtainItemQuest
{
    protected override int ItemType => ItemID.MechanicalEye;
}

public sealed class CraftMechanicalSkull : ObtainItemQuest
{
    protected override int ItemType => ItemID.MechanicalSkull;
}

public sealed class ObtainSoulsOfMight : ObtainItemQuest
{
    protected override int ItemType => ItemID.SoulofMight;

    protected override int Stack => 5;
}

public sealed class ObtainSoulsOfSight : ObtainItemQuest
{
    protected override int ItemType => ItemID.SoulofSight;

    protected override int Stack => 5;
}

public sealed class ObtainSoulsOfFright : ObtainItemQuest
{
    protected override int ItemType => ItemID.SoulofFright;

    protected override int Stack => 5;
}

public sealed class ObtainHallowedBars : ObtainItemQuest
{
    protected override int ItemType => ItemID.HallowedBar;

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.LifeforcePotion;

    protected internal override int RewardStack => 2;
}

public sealed class SetHallowedArmorMelee : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.HallowedMask, ItemID.HallowedPlateMail, ItemID.HallowedGreaves];

    protected internal override int RewardType => ItemID.WarriorEmblem;
}

public sealed class FarmEssenceOfEleum : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.EssenceofEleum>();

    protected override int Stack => 14;

    protected internal override int RewardType => ItemID.WarmthPotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmFragmentOfPermafrost : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.FragmentOfPermafrost>();

    protected override int Stack => 30;

    protected internal override int RewardType => ItemID.IronskinPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftCryoKey : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.CryoKey>();
}

public sealed class MineCryonicOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.CryonicOre>();

    protected override int Stack => 24;

    protected internal override int RewardType => ItemID.MiningPotion;

    protected internal override int RewardStack => 3;
}

public sealed class ObtainAdamantiteForge : ObtainItemQuest
{
    protected override int ItemType => ItemID.AdamantiteForge;
}

public sealed class ObtainTitaniumForge : ObtainItemQuest
{
    protected override int ItemType => ItemID.TitaniumForge;
}

public sealed class CraftCryonicBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.CryonicBar>();

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.EndurancePotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetDaedalusArmorRanged : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Daedalus.DaedalusHeadRanged>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Daedalus.DaedalusBreastplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Daedalus.DaedalusLeggings>()];

    protected internal override int RewardType => ItemID.MagicQuiver;
}

public sealed class EquipOrnateShield : EquipItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Accessories.OrnateShield>();
}

public sealed class ObtainDissolvingAurora : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.DissolvingAurora>();
}

public sealed class CraftFrostedKey : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Permafrost.FrostedKey>();
}

public sealed class ObtainSoulOfPlight : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Permafrost.SoulOfPlight>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.GreaterHealingPotion;

    protected internal override int RewardStack => 5;
}

public sealed class CraftAbsoluteBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Permafrost.AbsoluteBar>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.EndurancePotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetFrostArtifactArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Permafrost.FrostArtifactHelmet>(), ModContent.ItemType<global::SOTS.Items.Permafrost.FrostArtifactChestplate>(), ModContent.ItemType<global::SOTS.Items.Permafrost.FrostArtifactTrousers>()];

    protected internal override int RewardType => ItemID.FrozenTurtleShell;
}

public sealed class FarmEssenceOfHavoc : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.EssenceofHavoc>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.InfernoPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftEyeofDesolation : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.EyeofDesolation>();
}

public sealed class ObtainAshesOfCalamity : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AshesofCalamity>();

    protected override int Stack => 25;

    protected internal override int RewardType => ItemID.HeartreachPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftUnholyCore : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.UnholyCore>();

    protected override int Stack => 12;
}

public sealed class CraftCharredIdol : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.CharredIdol>();
}

public sealed class SetBrimflameArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Brimflame.BrimflameCowl>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Brimflame.BrimflameRobes>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Brimflame.BrimflameBoots>()];

    protected internal override int RewardType => ItemID.SorcererEmblem;
}

public sealed class CraftSeafood : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.Seafood>();
}

public sealed class ObtainGelatinCrystal : ObtainItemQuest
{
    protected override int ItemType => ItemID.QueenSlimeCrystal;
}

public sealed class ObtainLivingShard : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.LivingShard>();

    protected override int Stack => 10;
}

public sealed class MinePerennialOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.PerennialOre>();

    protected override int Stack => 24;

    protected internal override int RewardType => ItemID.MiningPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftPerennialBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.PerennialBar>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.RegenerationPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetReaverArmorTank : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Reaver.ReaverHeadTank>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Reaver.ReaverScaleMail>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Reaver.ReaverCuisses>()];

    protected internal override int RewardType => ItemID.PaladinsShield;
}

public sealed class ObtainEctoplasm : ObtainItemQuest
{
    protected override int ItemType => ItemID.Ectoplasm;

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.SpelunkerPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetSpectreArmor : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.SpectreHood, ItemID.SpectreRobe, ItemID.SpectrePants];

    protected internal override int RewardType => ItemID.CelestialEmblem;
}

public sealed class FarmEssenceOfSunlight : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.EssenceofSunlight>();

    protected override int Stack => 12;

    protected internal override int RewardType => ItemID.FeatherfallPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftCoreOfCalamity : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.CoreofCalamity>();
}

public sealed class EquipAsgardsValor : EquipItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Accessories.AsgardsValor>();
}

public sealed class ObtainLihzahrdPowerCell : ObtainItemQuest
{
    protected override int ItemType => ItemID.LihzahrdPowerCell;
}

public sealed class MineScoriaOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.ScoriaOre>();

    protected override int Stack => 24;

    protected internal override int RewardType => ItemID.GillsPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftScoriaBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.ScoriaBar>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.WrathPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetHydrothermicArmorMelee : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Hydrothermic.HydrothermicHeadMelee>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Hydrothermic.HydrothermicArmor>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Hydrothermic.HydrothermicSubligar>()];

    protected internal override int RewardType => ItemID.FireGauntlet;
}

public sealed class CraftLifeAlloy : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.LifeAlloy>();

    protected override int Stack => 12;

    protected internal override int RewardType => ItemID.LifeforcePotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftElectromagneticLure : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.ElectromagneticLure>();
}

public sealed class FarmFragmentOfChaos : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Fragments.FragmentOfChaos>();

    protected override int Stack => 12;
}

public sealed class ObtainPhaseOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Chaos.PhaseOre>();

    protected override int Stack => 60;
}

public sealed class CraftPhaseBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Chaos.PhaseBar>();

    protected override int Stack => 9;
}

public sealed class SetElementalArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Chaos.ElementalHelmet>(), ModContent.ItemType<global::SOTS.Items.Chaos.ElementalBreastplate>(), ModContent.ItemType<global::SOTS.Items.Chaos.ElementalLeggings>()];

    protected internal override int RewardType => ItemID.PapyrusScarab;
}

public sealed class CraftDecryptionComputer : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.DraedonMisc.DecryptionComputer>();
}

public sealed class CraftAstralChunk : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.AstralChunk>();
}

public sealed class ObtainAureusCell : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Potions.AureusCell>();

    protected override int Stack => 8;
}

public sealed class EquipLeviathanAmbergris : EquipItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Accessories.LeviathanAmbergris>();
}

public sealed class ObtainTruffleWorm : ObtainItemQuest
{
    protected override int ItemType => ItemID.TruffleWorm;
}

public sealed class ObtainPrismaticLacewing : ObtainItemQuest
{
    protected override int ItemType => ItemID.EmpressButterfly;
}

public sealed class FarmPlagueCellCanister : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.PlagueCellCanister>();

    protected override int Stack => 30;
}

public sealed class CraftAbombination : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.Abombination>();
}

public sealed class SetPlaguebringerArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Plaguebringer.PlaguebringerVisor>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Plaguebringer.PlaguebringerCarapace>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Plaguebringer.PlaguebringerPistons>()];

    protected internal override int RewardType => ItemID.PygmyNecklace;
}

public sealed class SetPlagueReaperArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.PlagueReaper.PlagueReaperMask>(), ModContent.ItemType<global::CalamityMod.Items.Armor.PlagueReaper.PlagueReaperVest>(), ModContent.ItemType<global::CalamityMod.Items.Armor.PlagueReaper.PlagueReaperStriders>()];

    protected internal override int RewardType => ItemID.ReconScope;
}

public sealed class CraftDeathWhistle : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.DeathWhistle>();
}

public sealed class ObtainAncientManipulator : ObtainItemQuest
{
    protected override int ItemType => ItemID.LunarCraftingStation;
}

public sealed class FarmMeldBlob : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.MeldBlob>();

    protected override int Stack => 8;

    protected internal override int RewardType => ItemID.RagePotion;

    protected internal override int RewardStack => 3;
}

public sealed class ObtainTitanHeart : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.TitanHeart>();
}

public sealed class MineAstralOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.AstralOre>();

    protected override int Stack => 24;

    protected internal override int RewardType => ItemID.SpelunkerPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftAstralBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AstralBar>();

    protected override int Stack => 15;

    protected internal override int RewardType => ItemID.TitanPotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetAstralArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Astral.AstralHelm>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Astral.AstralBreastplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Astral.AstralLeggings>()];

    protected internal override int RewardType => ItemID.CelestialStone;
}

public sealed class CraftStarcore : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.Starcore>();
}

public sealed class SetTitanHeartArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.TitanHeart.TitanHeartMask>(), ModContent.ItemType<global::CalamityMod.Items.Armor.TitanHeart.TitanHeartMantle>(), ModContent.ItemType<global::CalamityMod.Items.Armor.TitanHeart.TitanHeartBoots>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.ElectriciansGlove>();
}

public sealed class CraftTorchBomb : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Earth.Glowmoth.TorchBomb>();

    protected override int Stack => 5;
}

public sealed class CraftCatalystBomb : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Celestial.CatalystBomb>();
}

public sealed class ObtainSanguiteBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::SOTS.Items.Celestial.SanguiteBar>();

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.GreaterHealingPotion;

    protected internal override int RewardStack => 5;
}

public sealed class SetVoidspaceArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::SOTS.Items.Celestial.VoidspaceMask>(), ModContent.ItemType<global::SOTS.Items.Celestial.VoidspaceBreastplate>(), ModContent.ItemType<global::SOTS.Items.Celestial.VoidspaceLeggings>()];

    protected internal override int RewardType => ItemID.RangerEmblem;
}

public sealed class ObtainLuminiteBars : ObtainItemQuest
{
    protected override int ItemType => ItemID.LunarBar;

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.SuperHealingPotion;

    protected internal override int RewardStack => 5;
}

public sealed class FarmUnholyEssence : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.UnholyEssence>();

    protected override int Stack => 70;

    protected internal override int RewardType => ItemID.InfernoPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftProfanedShard : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.ProfanedShard>();
}

public sealed class ObtainProfanedCore : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.ProfanedCore>();
}

public sealed class ObtainDivineGeode : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.DivineGeode>();

    protected override int Stack => 25;

    protected internal override int RewardType => ItemID.LifeforcePotion;

    protected internal override int RewardStack => 3;
}

public sealed class MineUelibloomOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.UelibloomOre>();

    protected override int Stack => 24;

    protected internal override int RewardType => ItemID.MiningPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftUelibloomBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.UelibloomBar>();

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.EndurancePotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetTarragonArmorMelee : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Tarragon.TarragonHeadMelee>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Tarragon.TarragonBreastplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Tarragon.TarragonLeggings>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.BadgeofBravery>();
}

public sealed class ObtainSolarFragments : ObtainItemQuest
{
    protected override int ItemType => ItemID.FragmentSolar;

    protected override int Stack => 25;
}

public sealed class CraftExoticPheromones : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.ExoticPheromones>();
}

public sealed class ObtainEffulgentFeather : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.EffulgentFeather>();

    protected override int Stack => 15;
}

public sealed class MineExodiumCluster : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.ExodiumCluster>();

    protected override int Stack => 25;
}

public sealed class FarmNecroplasm : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.Necroplasm>();

    protected override int Stack => 50;

    protected internal override int RewardType => ItemID.SpelunkerPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftNecroplasmicBeacon : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.NecroplasmicBeacon>();
}

public sealed class ObtainRuinousSoul : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.RuinousSoul>();

    protected override int Stack => 8;
}

public sealed class SetBloodflareArmorRanged : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Bloodflare.BloodflareHeadRanged>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Bloodflare.BloodflareBodyArmor>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Bloodflare.BloodflareCuisses>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.DeadshotBrooch>();
}

public sealed class ObtainBloodworm : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.BloodwormItem>();
}

public sealed class CraftMarkOfProvidence : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.MarkofProvidence>();
}

public sealed class ObtainDarkPlasma : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.DarkPlasma>();
}

public sealed class ObtainArmoredShell : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.ArmoredShell>();
}

public sealed class ObtainTwistingNether : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.TwistingNether>();
}

public sealed class CraftCosmicWorm : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.CosmicWorm>();
}

public sealed class SetPrismaticArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Prismatic.PrismaticHelmet>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Prismatic.PrismaticRegalia>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Prismatic.PrismaticGreaves>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.SigilofCalamitas>();
}

public sealed class SetEmpyreanArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Empyrean.EmpyreanMask>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Empyrean.EmpyreanCloak>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Empyrean.EmpyreanCuisses>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.DarkMatterSheath>();
}

public sealed class SetSolarFlareArmor : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.SolarFlareHelmet, ItemID.SolarFlareBreastplate, ItemID.SolarFlareLeggings];

    protected internal override int RewardType => ItemID.CelestialShell;
}

public sealed class SetVortexArmor : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.VortexHelmet, ItemID.VortexBreastplate, ItemID.VortexLeggings];

    protected internal override int RewardType => ItemID.SniperScope;
}

public sealed class SetNebulaArmor : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.NebulaHelmet, ItemID.NebulaBreastplate, ItemID.NebulaLeggings];

    protected internal override int RewardType => ItemID.ManaCloak;
}

public sealed class SetStardustArmor : EquipSetQuest
{
    protected override int[] Pieces => [ItemID.StardustHelmet, ItemID.StardustBreastplate, ItemID.StardustLeggings];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.StatisBlessing>();
}

public sealed class ObtainCosmiliteBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.CosmiliteBar>();

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.SuperHealingPotion;

    protected internal override int RewardStack => 5;
}

public sealed class CraftCosmicAnvil : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Furniture.CraftingStations.CosmicAnvilItem>();
}

public sealed class FarmNightmareFuel : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.NightmareFuel>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.WrathPotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmEndothermicEnergy : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.EndothermicEnergy>();

    protected override int Stack => 50;

    protected internal override int RewardType => ItemID.EndurancePotion;

    protected internal override int RewardStack => 3;
}

public sealed class FarmDarksunFragment : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.DarksunFragment>();

    protected override int Stack => 10;

    protected internal override int RewardType => ItemID.RagePotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftAscendantSpiritEssence : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AscendantSpiritEssence>();

    protected override int Stack => 8;
}

public sealed class SetGodSlayerArmorMelee : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.GodSlayer.GodSlayerHeadMelee>(), ModContent.ItemType<global::CalamityMod.Items.Armor.GodSlayer.GodSlayerChestplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.GodSlayer.GodSlayerLeggings>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.BadgeofBravery>();
}

public sealed class SetSilvaArmorSummon : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Silva.SilvaHeadSummon>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Silva.SilvaArmor>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Silva.SilvaLeggings>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.StatisCurse>();
}

public sealed class SetFearmongerArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Fearmonger.FearmongerGreathelm>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Fearmonger.FearmongerPlateMail>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Fearmonger.FearmongerGreaves>()];

    protected internal override int RewardType => ItemID.PapyrusScarab;
}

public sealed class EquipElementalGauntlet : EquipItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Accessories.ElementalGauntlet>();
}

public sealed class CraftYharonEgg : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.YharonEgg>();
}

public sealed class ObtainYharonSoulFragment : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.YharonSoulFragment>();

    protected override int Stack => 5;
}

public sealed class ObtainAuricOre : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Ores.AuricOre>();

    protected override int Stack => 100;

    protected internal override int RewardType => ItemID.SpelunkerPotion;

    protected internal override int RewardStack => 3;
}

public sealed class CraftAuricBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AuricBar>();

    protected override int Stack => 20;

    protected internal override int RewardType => ItemID.LifeforcePotion;

    protected internal override int RewardStack => 3;
}

public sealed class SetAuricTeslaArmorMelee : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Auric.AuricTeslaHeadMelee>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Auric.AuricTeslaBodyArmor>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Auric.AuricTeslaCuisses>()];

    protected internal override int RewardType => ItemID.FireGauntlet;
}

public sealed class CraftCodebreakerBase : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.DraedonMisc.CodebreakerBase>();
}

public sealed class CraftVoltageRegulationSystem : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.DraedonMisc.VoltageRegulationSystem>();
}

public sealed class CraftAuricQuantumCoolingCell : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.DraedonMisc.AuricQuantumCoolingCell>();
}

public sealed class CraftAltarOfTheAccursed : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Furniture.CraftingStations.AltarOfTheAccursedItem>();
}

public sealed class GatherAshesOfCalamity : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AshesofCalamity>();
}

public sealed class ObtainAshesOfAnnihilation : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.AshesofAnnihilation>();

    protected override int Stack => 10;
}

public sealed class CraftCeremonialUrn : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.SummonItems.CeremonialUrn>();
}

public sealed class ObtainExoPrism : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.ExoPrism>();

    protected override int Stack => 12;
}

public sealed class CraftDraedonsForge : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Placeables.Furniture.CraftingStations.DraedonsForge>();
}

public sealed class CraftShadowspecBar : ObtainItemQuest
{
    protected override int ItemType => ModContent.ItemType<global::CalamityMod.Items.Materials.ShadowspecBar>();

    protected override int Stack => 18;
}

public sealed class SetDemonshadeArmor : EquipSetQuest
{
    protected override int[] Pieces => [ModContent.ItemType<global::CalamityMod.Items.Armor.Demonshade.DemonshadeHelm>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Demonshade.DemonshadeBreastplate>(), ModContent.ItemType<global::CalamityMod.Items.Armor.Demonshade.DemonshadeGreaves>()];

    protected internal override int RewardType => ModContent.ItemType<global::CalamityMod.Items.Accessories.Nucleogenesis>();
}
