// <auto-generated>
//     Generated by tools/generate_quests.py from tools/quest_steps.json.
// </auto-generated>

namespace BereftSouls.Quests;

internal sealed partial class ProgressionBook
{
    private static readonly Node[] pre_hardmode_first_steps =
    [
        new("ObtainLeadBars", 0, -4, NodeKind.Step, false),
        new("CraftFrigidBar", 0, -3, NodeKind.Step, false),
        new("SetSnowRuffianArmor", 0, -2, NodeKind.Step, false),
        new("FarmFragmentOfEarth", 0, -1, NodeKind.Step, false),
        new("KingSlimeDefeated", 0, 0, NodeKind.Required, false),
        new("ObtainPrismShard", 0, 1, NodeKind.Step, false),
        new("EquipMarniteRepulsionShield", 0, 2, NodeKind.Step, false),
        new("FarmWulfrumScrap", 0, 3, NodeKind.Step, false),
        new("ObtainIronBars", 0, 4, NodeKind.Step, false),
        new("SetLeadArmor", 1, -4, NodeKind.Step, false, "ObtainLeadBars"),
        new("SetFrigidArmor", 1, -3, NodeKind.Step, false, "CraftFrigidBar"),
        new("CraftSuspiciousLookingCandle", 1, 0, NodeKind.Step, false, "ObtainPrismShard", "KingSlimeDefeated"),
        new("CraftVibrantBar", 1, 1, NodeKind.Step, false, "FarmFragmentOfEarth"),
        new("SetWulfrumArmor", 1, 2, NodeKind.Step, false, "FarmWulfrumScrap"),
        new("CraftWulfrumProsthesis", 1, 3, NodeKind.Step, false, "FarmWulfrumScrap"),
        new("CraftWulfrumKnife", 1, 4, NodeKind.Step, false, "FarmWulfrumScrap"),
        new("SetIronArmor", 1, 5, NodeKind.Step, false, "ObtainIronBars"),
        new("GlowmothDefeated", 2, 0, NodeKind.Required, false, "CraftSuspiciousLookingCandle"),
        new("FarmStormlionMandible", 2, 1, NodeKind.Step, false),
        new("SetVibrantArmor", 2, 2, NodeKind.Step, false, "CraftVibrantBar"),
        new("CraftDesertMedallion", 3, 0, NodeKind.Step, false, "FarmStormlionMandible", "FarmFragmentOfEarth", "GlowmothDefeated"),
        new("DesertScourgeDefeated", 4, 0, NodeKind.Required, false, "CraftDesertMedallion"),
    ];

    private static readonly Node[] pre_hardmode_the_eye =
    [
        new("FarmLens", 0, 0, NodeKind.Step, false),
        new("FarmFragmentOfTide", 0, 1, NodeKind.Step, false),
        new("ObtainPearlShard", 0, 2, NodeKind.Step, false),
        new("CraftSuspiciousLookingEye", 1, 0, NodeKind.Step, false, "FarmLens"),
        new("SetVictideArmorMelee", 1, 1, NodeKind.Step, false, "ObtainPearlShard", "FarmFragmentOfTide"),
        new("EyeOfCthulhuDefeated", 2, 0, NodeKind.Required, false, "CraftSuspiciousLookingEye"),
        new("FarmFragmentOfNature", 2, 1, NodeKind.Step, false),
        new("CraftDecapoditaSprout", 3, 0, NodeKind.Step, false, "FarmFragmentOfNature", "EyeOfCthulhuDefeated"),
        new("CrabulonDefeated", 4, 0, NodeKind.Required, false, "CraftDecapoditaSprout"),
    ];

    private static readonly Node[] pre_hardmode_world_evil =
    [
        new("EvilBossDefeated", 0, 0, NodeKind.Required, false),
        new("EquipFungalClump", 0, 1, NodeKind.Step, false),
        new("ObtainHellforge", 1, -1, NodeKind.Step, false, "EvilBossDefeated"),
        new("HiveMindDefeated", 1, 0, NodeKind.Required, false, "EvilBossDefeated"),
        new("PerforatorsDefeated", 1, 1, NodeKind.Required, false, "EvilBossDefeated"),
        new("CraftHellstoneBars", 2, -1, NodeKind.Step, false, "ObtainHellforge"),
        new("SetMoltenArmor", 3, -1, NodeKind.Step, false, "CraftHellstoneBars"),
    ];

    private static readonly Node[] pre_hardmode_hive_and_pyramid =
    [
        new("CraftAbeemination", 0, 0, NodeKind.Step, true),
        new("FarmFragmentOfOtherworld", 0, 1, NodeKind.Step, false),
        new("MineAerialiteOre", 0, 2, NodeKind.Step, true),
        new("QueenBeeDefeated", 1, 0, NodeKind.Required, false, "CraftAbeemination"),
        new("FarmPeanuts", 1, 1, NodeKind.Step, false),
        new("CraftAerialiteBar", 1, 2, NodeKind.Step, false, "MineAerialiteOre", "FarmFragmentOfOtherworld"),
        new("ObtainBeeWax", 2, 0, NodeKind.Step, false, "QueenBeeDefeated"),
        new("CraftJarOfPeanuts", 2, 1, NodeKind.Step, false, "CraftAerialiteBar", "FarmPeanuts", "QueenBeeDefeated"),
        new("SetAerospecArmorRogue", 2, 2, NodeKind.Step, false, "CraftAerialiteBar"),
        new("PutridPinkyDefeated", 3, 0, NodeKind.Required, false, "CraftJarOfPeanuts"),
        new("ObtainSolidifier", 3, 1, NodeKind.Step, false),
        new("PharaohsCurseDefeated", 4, 0, NodeKind.Required, false, "PutridPinkyDefeated"),
        new("ObtainWormwood", 4, 1, NodeKind.Step, true, "PutridPinkyDefeated", "ObtainSolidifier"),
        new("FarmSulphuricScale", 4, 2, NodeKind.Step, false),
        new("SetNatureArmor", 5, 2, NodeKind.Step, false, "ObtainWormwood", "FarmSulphuricScale"),
    ];

    private static readonly Node[] pre_hardmode_dungeon =
    [
        new("SkeletronDefeated", 0, 0, NodeKind.Required, false),
        new("ObtainCursedMatter", 0, 1, NodeKind.Step, false),
        new("CraftDeerThing", 1, 0, NodeKind.Step, false, "SkeletronDefeated"),
        new("SetCursedArmor", 1, 1, NodeKind.Step, false, "ObtainCursedMatter"),
        new("DeerclopsDefeated", 2, 0, NodeKind.Required, false, "CraftDeerThing"),
        new("FarmBlightedGel", 2, 1, NodeKind.Step, false),
        new("CraftOverloadedSludge", 3, 0, NodeKind.Step, false, "FarmBlightedGel", "DeerclopsDefeated"),
        new("SlimeGodDefeated", 4, 0, NodeKind.Required, false, "CraftOverloadedSludge"),
    ];

    private static readonly Node[] pre_hardmode_underworld =
    [
        new("ExcavatorDefeated", 0, 0, NodeKind.Required, false),
        new("ObtainPurifiedGel", 0, 1, NodeKind.Step, false),
        new("ObtainEarthenPlating", 1, -1, NodeKind.Step, false, "ExcavatorDefeated"),
        new("AdvisorDefeated", 1, 0, NodeKind.Required, false, "ExcavatorDefeated"),
        new("ObtainGuideVoodooDoll", 1, 1, NodeKind.Step, false),
        new("SetStatigelArmorMagic", 1, 2, NodeKind.Step, false, "ObtainPurifiedGel"),
        new("CraftFleshboundEffigy", 2, 0, NodeKind.Step, false, "ObtainGuideVoodooDoll", "AdvisorDefeated"),
        new("ObtainHardlightFabricator", 2, 1, NodeKind.Step, false, "AdvisorDefeated"),
        new("WallOfFleshDefeated", 3, 0, NodeKind.Gate, false, "CraftFleshboundEffigy"),
        new("CraftStarlightAlloy", 3, 1, NodeKind.Step, false, "ObtainHardlightFabricator"),
        new("SetTwilightAssassinArmor", 4, 1, NodeKind.Step, false, "CraftStarlightAlloy", "ObtainPurifiedGel"),
    ];

    private static readonly Node[] early_hardmode_new_world =
    [
        new("ObtainGelatinCrystal", 0, -1, NodeKind.Step, false),
        new("FarmSoulsOfLight", 0, 0, NodeKind.Step, false),
        new("FarmSoulsOfNight", 0, 1, NodeKind.Step, false),
        new("FarmEssenceOfEleum", 1, -1, NodeKind.Step, false),
        new("QueenSlimeDefeated", 1, 0, NodeKind.Required, false, "ObtainGelatinCrystal"),
        new("ObtainOrichalcumAnvil", 1, 1, NodeKind.Step, false, "FarmSoulsOfLight", "FarmSoulsOfNight"),
        new("FarmFragmentOfPermafrost", 1, 2, NodeKind.Step, false),
        new("CraftCryoKey", 2, 0, NodeKind.Step, false, "FarmEssenceOfEleum", "FarmFragmentOfPermafrost", "FarmSoulsOfLight", "FarmSoulsOfNight", "QueenSlimeDefeated"),
        new("CryogenDefeated", 3, 0, NodeKind.Required, false, "CraftCryoKey"),
        new("CraftSeafood", 4, 0, NodeKind.Step, false, "CryogenDefeated"),
        new("MineCryonicOre", 4, 1, NodeKind.Step, false, "CryogenDefeated"),
        new("AquaticScourgeDefeated", 5, 0, NodeKind.Required, false, "CraftSeafood"),
        new("ObtainAdamantiteForge", 5, 1, NodeKind.Step, false, "MineCryonicOre"),
        new("ObtainTitaniumForge", 5, 2, NodeKind.Step, false, "MineCryonicOre"),
        new("CraftCryonicBar", 6, 2, NodeKind.Step, true, "ObtainAdamantiteForge", "ObtainTitaniumForge"),
        new("EquipOrnateShield", 7, 2, NodeKind.Step, false, "CraftCryonicBar"),
        new("SetDaedalusArmorRanged", 7, 3, NodeKind.Step, false, "CraftCryonicBar"),
    ];

    private static readonly Node[] early_hardmode_mechanical =
    [
        new("FarmEssenceOfHavoc", 0, 0, NodeKind.Step, false),
        new("CraftUnholyCore", 1, 0, NodeKind.Step, false, "FarmEssenceOfHavoc"),
        new("CraftCharredIdol", 2, 0, NodeKind.Step, false, "CraftUnholyCore"),
        new("BrimstoneElementalDefeated", 3, 0, NodeKind.Required, false, "CraftCharredIdol"),
        new("ObtainMythrilAnvil", 3, 1, NodeKind.Step, false),
        new("CraftMechanicalWorm", 4, 0, NodeKind.Step, false, "BrimstoneElementalDefeated", "ObtainMythrilAnvil"),
        new("TheDestroyerDefeated", 5, 0, NodeKind.Required, false, "CraftMechanicalWorm"),
        new("CraftMechanicalEye", 6, 0, NodeKind.Step, false, "TheDestroyerDefeated", "ObtainMythrilAnvil"),
        new("TheTwinsDefeated", 7, 0, NodeKind.Required, false, "CraftMechanicalEye"),
        new("CraftMechanicalSkull", 8, 0, NodeKind.Step, false, "TheTwinsDefeated", "ObtainMythrilAnvil"),
        new("SkeletronPrimeDefeated", 9, 0, NodeKind.Required, false, "CraftMechanicalSkull"),
    ];

    private static readonly Node[] early_hardmode_calamitys_shadow =
    [
        new("ObtainHallowedBars", 0, -2, NodeKind.Step, true),
        new("ObtainSoulsOfFright", 0, -1, NodeKind.Step, false),
        new("ObtainSoulsOfMight", 0, 0, NodeKind.Step, false),
        new("ObtainSoulsOfSight", 0, 1, NodeKind.Step, false),
        new("ObtainDissolvingAurora", 0, 2, NodeKind.Step, false),
        new("SetHallowedArmorMelee", 1, -2, NodeKind.Step, false, "ObtainHallowedBars"),
        new("CraftFrostedKey", 1, 0, NodeKind.Step, false, "ObtainDissolvingAurora", "ObtainSoulsOfMight", "ObtainSoulsOfSight", "ObtainSoulsOfFright"),
        new("PolarisDefeated", 2, 0, NodeKind.Required, false, "CraftFrostedKey"),
        new("ObtainSoulOfPlight", 3, 0, NodeKind.Step, false, "PolarisDefeated"),
        new("CraftEyeofDesolation", 4, 0, NodeKind.Step, false, "ObtainSoulOfPlight", "PolarisDefeated"),
        new("CraftAbsoluteBar", 4, 1, NodeKind.Step, false, "ObtainSoulOfPlight", "ObtainHallowedBars"),
        new("CalamitasCloneDefeated", 5, 0, NodeKind.Required, false, "CraftEyeofDesolation"),
        new("SetFrostArtifactArmor", 5, 1, NodeKind.Step, false, "CraftAbsoluteBar"),
        new("PlanteraDefeated", 6, 0, NodeKind.Gate, false, "CalamitasCloneDefeated"),
        new("ObtainAshesOfCalamity", 6, 1, NodeKind.Step, false, "CalamitasCloneDefeated"),
        new("SetBrimflameArmor", 7, 1, NodeKind.Step, false, "ObtainAshesOfCalamity"),
    ];

    private static readonly Node[] post_plantera_depths_and_stars =
    [
        new("FarmEssenceOfSunlight", 0, -3, NodeKind.Step, false),
        new("ObtainEctoplasm", 0, -2, NodeKind.Step, false),
        new("CraftDecryptionComputer", 0, -1, NodeKind.Step, false),
        new("LeviathanDefeated", 0, 0, NodeKind.Required, false),
        new("MinePerennialOre", 0, 1, NodeKind.Step, false),
        new("ObtainLivingShard", 0, 2, NodeKind.Step, false),
        new("ObtainTitanHeart", 0, 3, NodeKind.Step, false),
        new("CraftCoreOfCalamity", 1, -3, NodeKind.Step, false, "ObtainEctoplasm", "FarmEssenceOfSunlight"),
        new("SetSpectreArmor", 1, -2, NodeKind.Step, false, "ObtainEctoplasm"),
        new("EquipLeviathanAmbergris", 1, -1, NodeKind.Step, false, "LeviathanDefeated"),
        new("CraftAstralChunk", 1, 0, NodeKind.Step, false, "CraftDecryptionComputer", "LeviathanDefeated"),
        new("CraftPerennialBar", 1, 1, NodeKind.Step, false, "MinePerennialOre"),
        new("SetTitanHeartArmor", 1, 3, NodeKind.Step, false, "ObtainTitanHeart"),
        new("EquipAsgardsValor", 2, -3, NodeKind.Step, false, "CraftCoreOfCalamity"),
        new("AstrumAureusDefeated", 2, 0, NodeKind.Required, false, "CraftAstralChunk"),
        new("ObtainLihzahrdPowerCell", 2, 1, NodeKind.Step, false),
        new("SetReaverArmorTank", 2, 2, NodeKind.Step, false, "CraftPerennialBar"),
        new("GolemDefeated", 3, 0, NodeKind.Required, false, "ObtainLihzahrdPowerCell", "AstrumAureusDefeated"),
    ];

    private static readonly Node[] post_plantera_jungle_and_sea =
    [
        new("FarmPlagueCellCanister", 0, 0, NodeKind.Step, false),
        new("MineScoriaOre", 0, 1, NodeKind.Step, false),
        new("SetPlagueReaperArmor", 1, -1, NodeKind.Step, false, "FarmPlagueCellCanister"),
        new("CraftAbombination", 1, 0, NodeKind.Step, false, "FarmPlagueCellCanister"),
        new("CraftScoriaBar", 1, 1, NodeKind.Step, false, "MineScoriaOre"),
        new("ObtainTruffleWorm", 2, -1, NodeKind.Step, false),
        new("PlaguebringerDefeated", 2, 0, NodeKind.Required, false, "CraftAbombination"),
        new("SetHydrothermicArmorMelee", 2, 1, NodeKind.Step, false, "CraftScoriaBar"),
        new("CraftSigilTruffleWorm", 3, 0, NodeKind.Step, false, "ObtainTruffleWorm", "PlaguebringerDefeated"),
        new("SetPlaguebringerArmor", 3, 1, NodeKind.Step, false, "PlaguebringerDefeated"),
        new("DukeFishronDefeated", 4, 0, NodeKind.Required, false, "CraftSigilTruffleWorm"),
        new("ObtainPrismaticLacewing", 4, 1, NodeKind.Step, false),
        new("EmpressOfLightDefeated", 5, 0, NodeKind.Required, false, "ObtainPrismaticLacewing", "DukeFishronDefeated"),
    ];

    private static readonly Node[] post_plantera_the_cult =
    [
        new("CraftDeathWhistle", 0, 0, NodeKind.Step, false),
        new("CraftLifeAlloy", 0, 1, NodeKind.Step, false),
        new("RavagerDefeated", 1, 0, NodeKind.Required, false, "CraftDeathWhistle"),
        new("CraftElectromagneticLure", 1, 1, NodeKind.Step, false, "CraftLifeAlloy"),
        new("LuxDefeated", 2, 0, NodeKind.Required, false, "CraftElectromagneticLure", "RavagerDefeated"),
        new("LunaticCultistDefeated", 3, 0, NodeKind.Required, false, "LuxDefeated"),
        new("ObtainPhaseOre", 3, 1, NodeKind.Step, false, "LuxDefeated"),
        new("FarmFragmentOfChaos", 3, 2, NodeKind.Step, false),
        new("CraftPhaseBar", 4, 1, NodeKind.Step, false, "ObtainPhaseOre", "FarmFragmentOfChaos"),
        new("SetElementalArmor", 5, 1, NodeKind.Step, false, "CraftPhaseBar"),
    ];

    private static readonly Node[] post_plantera_celestial_ascent =
    [
        new("AstrumDeusDefeated", 0, 0, NodeKind.Required, false),
        new("FarmMeldBlob", 1, 0, NodeKind.Step, false, "AstrumDeusDefeated"),
        new("CraftTorchBomb", 1, 1, NodeKind.Step, false),
        new("ObtainAncientManipulator", 1, 2, NodeKind.Step, false),
        new("MineAstralOre", 1, 3, NodeKind.Step, false, "AstrumDeusDefeated"),
        new("CraftCatalystBomb", 2, 0, NodeKind.Step, false, "CraftTorchBomb", "FarmMeldBlob", "AstrumDeusDefeated"),
        new("ObtainAureusCell", 2, 2, NodeKind.Step, false),
        new("CraftAstralBar", 2, 3, NodeKind.Step, false, "MineAstralOre", "ObtainAncientManipulator"),
        new("SubspaceSerpentDefeated", 3, 0, NodeKind.Required, false, "CraftCatalystBomb"),
        new("CraftStarcore", 3, 2, NodeKind.Step, false, "CraftAstralBar", "ObtainAureusCell"),
        new("SetAstralArmor", 3, 3, NodeKind.Step, false, "CraftAstralBar"),
        new("MoonLordDefeated", 4, 0, NodeKind.Gate, false, "SubspaceSerpentDefeated"),
        new("ObtainSanguiteBar", 4, 1, NodeKind.Step, false, "SubspaceSerpentDefeated"),
        new("SetVoidspaceArmor", 5, 2, NodeKind.Step, false, "ObtainSanguiteBar", "CraftAstralBar"),
    ];

    private static readonly Node[] post_moon_lord_the_profaned =
    [
        new("FarmUnholyEssence", 0, 0, NodeKind.Step, false),
        new("ObtainLuminiteBars", 0, 1, NodeKind.Step, false),
        new("SetNebulaArmor", 1, -1, NodeKind.Step, false, "ObtainLuminiteBars"),
        new("CraftProfanedShard", 1, 0, NodeKind.Step, false, "ObtainLuminiteBars", "FarmUnholyEssence"),
        new("SetEmpyreanArmor", 1, 1, NodeKind.Step, false, "ObtainLuminiteBars"),
        new("SetSolarFlareArmor", 1, 2, NodeKind.Step, false, "ObtainLuminiteBars"),
        new("SetVortexArmor", 1, 3, NodeKind.Step, false, "ObtainLuminiteBars"),
        new("SetStardustArmor", 1, 4, NodeKind.Step, false, "ObtainLuminiteBars"),
        new("ProfanedGuardiansDefeated", 2, 0, NodeKind.Required, false, "CraftProfanedShard"),
        new("ObtainSolarFragments", 2, 1, NodeKind.Step, false),
        new("CraftExoticPheromones", 3, 0, NodeKind.Step, false, "ObtainSolarFragments", "ProfanedGuardiansDefeated"),
        new("DragonfollyDefeated", 4, 0, NodeKind.Required, false, "CraftExoticPheromones"),
        new("ObtainProfanedCore", 4, 1, NodeKind.Step, false, "ProfanedGuardiansDefeated"),
        new("ProvidenceDefeated", 5, 0, NodeKind.Required, false, "ObtainProfanedCore", "DragonfollyDefeated"),
        new("ObtainEffulgentFeather", 5, 1, NodeKind.Step, false, "DragonfollyDefeated"),
    ];

    private static readonly Node[] post_moon_lord_the_sentinels =
    [
        new("CraftMarkOfProvidence", 0, 0, NodeKind.Step, false),
        new("MineUelibloomOre", 0, 2, NodeKind.Step, false),
        new("SignusDefeated", 1, -1, NodeKind.Required, false, "CraftMarkOfProvidence"),
        new("CeaselessVoidDefeated", 1, 0, NodeKind.Required, false, "CraftMarkOfProvidence"),
        new("StormWeaverDefeated", 1, 1, NodeKind.Required, false, "CraftMarkOfProvidence"),
        new("CraftUelibloomBar", 1, 2, NodeKind.Step, false, "MineUelibloomOre"),
        new("ObtainDivineGeode", 1, 3, NodeKind.Step, false),
        new("MineExodiumCluster", 2, 0, NodeKind.Step, false),
        new("ObtainArmoredShell", 2, 1, NodeKind.Step, false, "StormWeaverDefeated"),
        new("SetTarragonArmorMelee", 2, 2, NodeKind.Step, false, "CraftUelibloomBar", "ObtainDivineGeode"),
        new("SetPrismaticArmor", 3, 1, NodeKind.Step, false, "ObtainArmoredShell", "ObtainDivineGeode", "MineExodiumCluster"),
    ];

    private static readonly Node[] post_moon_lord_the_devourer =
    [
        new("FarmNecroplasm", 0, 0, NodeKind.Step, false),
        new("CraftNecroplasmicBeacon", 1, 0, NodeKind.Step, false, "FarmNecroplasm"),
        new("PolterghastDefeated", 2, 0, NodeKind.Required, false, "CraftNecroplasmicBeacon"),
        new("ObtainBloodworm", 2, 1, NodeKind.Step, false),
        new("CraftSigilBloodworm", 3, 0, NodeKind.Step, false, "ObtainBloodworm", "PolterghastDefeated"),
        new("ObtainRuinousSoul", 3, 1, NodeKind.Step, false, "PolterghastDefeated"),
        new("ObtainDarkPlasma", 4, -1, NodeKind.Step, false),
        new("OldDukeDefeated", 4, 0, NodeKind.Required, false, "CraftSigilBloodworm"),
        new("SetBloodflareArmorRanged", 4, 1, NodeKind.Step, false, "ObtainRuinousSoul"),
        new("ObtainTwistingNether", 4, 2, NodeKind.Step, false),
        new("CraftCosmicWorm", 5, 0, NodeKind.Step, false, "ObtainDarkPlasma", "ObtainTwistingNether", "OldDukeDefeated"),
        new("DevourerOfGodsDefeated", 6, 0, NodeKind.Gate, false, "CraftCosmicWorm"),
    ];

    private static readonly Node[] endgame_dragon_and_witch =
    [
        new("FarmDarksunFragment", 0, -3, NodeKind.Step, false),
        new("FarmNightmareFuel", 0, -2, NodeKind.Step, false),
        new("FarmEndothermicEnergy", 0, -1, NodeKind.Step, false),
        new("CraftYharonEgg", 0, 0, NodeKind.Step, false),
        new("ObtainCosmiliteBar", 0, 1, NodeKind.Step, false),
        new("CraftAscendantSpiritEssence", 1, -1, NodeKind.Step, false, "FarmNightmareFuel", "FarmEndothermicEnergy", "FarmDarksunFragment"),
        new("YharonDefeated", 1, 0, NodeKind.Required, false, "CraftYharonEgg"),
        new("CraftCosmicAnvil", 1, 1, NodeKind.Step, false, "ObtainCosmiliteBar"),
        new("SetFearmongerArmor", 2, -2, NodeKind.Step, false, "CraftAscendantSpiritEssence", "CraftCosmicAnvil"),
        new("SetGodSlayerArmorMelee", 2, -1, NodeKind.Step, false, "CraftAscendantSpiritEssence", "CraftCosmicAnvil"),
        new("GatherAshesOfCalamity", 2, 0, NodeKind.Step, false, "YharonDefeated"),
        new("ObtainYharonSoulFragment", 2, 1, NodeKind.Step, false, "YharonDefeated"),
        new("SetSilvaArmorSummon", 2, 2, NodeKind.Step, false, "CraftAscendantSpiritEssence", "CraftCosmicAnvil"),
        new("EquipElementalGauntlet", 2, 3, NodeKind.Step, false, "CraftAscendantSpiritEssence", "CraftCosmicAnvil"),
        new("SupremeCalamitasDefeated", 3, 0, NodeKind.Gate, false, "GatherAshesOfCalamity"),
        new("ObtainAuricOre", 3, 1, NodeKind.Step, false, "ObtainYharonSoulFragment"),
        new("CraftAuricBar", 4, 1, NodeKind.Step, false, "ObtainAuricOre"),
        new("SetAuricTeslaArmorMelee", 5, 1, NodeKind.Step, false, "CraftAuricBar", "CraftCosmicAnvil"),
        new("CraftAltarOfTheAccursed", 5, 2, NodeKind.Step, false, "CraftAuricBar"),
    ];

    private static readonly Node[] endgame_draedons_arsenal =
    [
        new("CraftCodebreakerBase", 0, 0, NodeKind.Step, false),
        new("ObtainAshesOfAnnihilation", 0, 1, NodeKind.Step, false),
        new("CraftVoltageRegulationSystem", 1, 0, NodeKind.Step, false, "CraftCodebreakerBase"),
        new("CraftCeremonialUrn", 1, 1, NodeKind.Step, false, "ObtainAshesOfAnnihilation"),
        new("CraftAuricQuantumCoolingCell", 2, 0, NodeKind.Step, false, "CraftVoltageRegulationSystem"),
        new("ExoMechsDefeated", 3, 0, NodeKind.Gate, false, "CraftCodebreakerBase", "CraftVoltageRegulationSystem", "CraftAuricQuantumCoolingCell"),
        new("ObtainExoPrism", 4, 0, NodeKind.Step, false, "ExoMechsDefeated"),
        new("CraftDraedonsForge", 5, 0, NodeKind.Step, false, "ObtainExoPrism"),
        new("CraftShadowspecBar", 6, 0, NodeKind.Step, false, "CraftDraedonsForge", "ObtainAshesOfAnnihilation"),
        new("SetDemonshadeArmor", 7, 0, NodeKind.Step, false, "CraftShadowspecBar"),
    ];

    /// <summary>Every section in pack order.</summary>
    private static readonly Section[] sections =
    [
        new("PreHardmode", "FirstSteps", pre_hardmode_first_steps),
        new("PreHardmode", "TheEye", pre_hardmode_the_eye, "KingSlimeDefeated", "GlowmothDefeated", "DesertScourgeDefeated"),
        new("PreHardmode", "WorldEvil", pre_hardmode_world_evil, "EyeOfCthulhuDefeated", "CrabulonDefeated"),
        new("PreHardmode", "HiveAndPyramid", pre_hardmode_hive_and_pyramid, "EvilBossDefeated", "HiveMindDefeated|PerforatorsDefeated"),
        new("PreHardmode", "Dungeon", pre_hardmode_dungeon, "QueenBeeDefeated", "PutridPinkyDefeated", "PharaohsCurseDefeated"),
        new("PreHardmode", "Underworld", pre_hardmode_underworld, "SkeletronDefeated", "DeerclopsDefeated", "SlimeGodDefeated"),
        new("EarlyHardmode", "NewWorld", early_hardmode_new_world, "ExcavatorDefeated", "AdvisorDefeated", "WallOfFleshDefeated"),
        new("EarlyHardmode", "Mechanical", early_hardmode_mechanical, "QueenSlimeDefeated", "CryogenDefeated", "AquaticScourgeDefeated"),
        new("EarlyHardmode", "CalamitysShadow", early_hardmode_calamitys_shadow, "BrimstoneElementalDefeated", "TheDestroyerDefeated", "TheTwinsDefeated", "SkeletronPrimeDefeated"),
        new("PostPlantera", "DepthsAndStars", post_plantera_depths_and_stars, "PolarisDefeated", "CalamitasCloneDefeated", "PlanteraDefeated"),
        new("PostPlantera", "JungleAndSea", post_plantera_jungle_and_sea, "LeviathanDefeated", "AstrumAureusDefeated", "GolemDefeated"),
        new("PostPlantera", "TheCult", post_plantera_the_cult, "PlaguebringerDefeated", "DukeFishronDefeated", "EmpressOfLightDefeated"),
        new("PostPlantera", "CelestialAscent", post_plantera_celestial_ascent, "RavagerDefeated", "LuxDefeated", "LunaticCultistDefeated"),
        new("PostMoonLord", "TheProfaned", post_moon_lord_the_profaned, "AstrumDeusDefeated", "SubspaceSerpentDefeated", "MoonLordDefeated"),
        new("PostMoonLord", "TheSentinels", post_moon_lord_the_sentinels, "ProfanedGuardiansDefeated", "DragonfollyDefeated", "ProvidenceDefeated"),
        new("PostMoonLord", "TheDevourer", post_moon_lord_the_devourer, "StormWeaverDefeated", "CeaselessVoidDefeated", "SignusDefeated"),
        new("Endgame", "DragonAndWitch", endgame_dragon_and_witch, "PolterghastDefeated", "OldDukeDefeated", "DevourerOfGodsDefeated"),
        new("Endgame", "DraedonsArsenal", endgame_draedons_arsenal, "YharonDefeated", "SupremeCalamitasDefeated"),
    ];
}
